# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multitenant_backend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    
    def forwards(apps, schema_editor):
        Tenant = apps.get_model("multitenant_backend", "Tenant")
        db_alias = schema_editor.connection.alias
        Tenant.objects.using(db_alias).bulk_create([
            Tenant(name="default", email="foo@bar.com")
        ])

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RunPython(forwards),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', multitenant_backend.models.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multitenant_backend.Tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
